allowBuilds:
  better-sqlite3: true
  esbuild: true
  lefthook: true
  msgpackr-extract: true
  protobufjs: true
blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@opencode/*"
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
