allowBuilds:
  esbuild: true
  lefthook: true
  msgpackr-extract: true
  protobufjs: false
blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
